windowrule = center 1, match:title ^(Authentication Required|Add Folder to Workspace|Save As|SDDM Background)$
windowrule = center 1, match:title ^(ROG Control|Keybindings)$
windowrule = float 1, match:class ^(org.gnome.Calculator)$, match:title (Calculator)
windowrule = float 1, match:class ^(Zoom|onedriver|onedriver-launcher)$
windowrule = float 1, match:title ^(Picture-in-Picture|Authentication Required|Save As|Add Folder to Workspace|Open Files|SDDM Background)$
windowrule = opacity 0.98 0.98, match:tag terminal*
windowrule = size 16% 12%, match:title ^(SDDM Background)$
windowrule = size 70% 60%, match:title ^(Add Folder to Workspace|Save As|Open Files)$
windowrule = tag +browser, match:class ^(chrome-.+-Default)$
windowrule = tag +projects, match:class ^(jetbrains-.+)$
windowrule = tag +settings, match:class ^(wihotspot(-gui)?|gnome-disks|file-roller|org.gnome.FileRoller|nm-applet|nm-connection-editor|blueman-manager|pavucontrol|org.pulseaudio.pavucontrol|qt5ct|qt6ct|[Yy]ad|xdg-desktop-portal-gtk|org.kde.polkit-kde-authentication-agent-1)$
windowrule = tag +settings, match:title ^(ROG Control|Kvantum Manager)$
windowrule = tag +viewer, match:class ^(gnome-system-monitor|org.gnome.SystemMonitor|io.missioncenter.MissionCenter|evince|eog|org.gnome.Loupe)$

# OpenClaw chat popup window rules
windowrule = float 1, match:class ^(floating-openclaw)$
windowrule = center 1, match:class ^(floating-openclaw)$
windowrule = opacity 0.95 0.95, match:class ^(floating-openclaw)$
