# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #E1E4E9
background         #00010E
cursor             #7A9CB2

active_tab_foreground     #00010E
active_tab_background     #E1E4E9
inactive_tab_foreground   #E1E4E9
inactive_tab_background   #00010E

active_border_color   #E1E4E9
inactive_border_color #00010E
bell_border_color     #0C3B57

color0      #000511
color1		#0C3B57
color2		#0E3F5C
color3		#464443
color4		#55463D
color5		#4B6477
color6		#7F858F
color7		#CCD0D7
color8		#8F9196
color9		#104E74
color10		#13547B
color11		#5E5A59
color12		#715D52
color13		#64859F
color14		#AAB1BF
color15		#CCD0D7
