import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import theme

SAMPLE = '''
-- Colors generated by wallust.
return {
    background = "rgb(00010E)",
    foreground = "rgb(E1E4E9)",
    color0     = "rgb(000511)",
    color7     = "rgb(CCD0D7)",
}
'''


def test_parses_named_colors():
    palette = theme.parse_palette(SAMPLE)
    assert palette["background"] == "#00010E"
    assert palette["foreground"] == "#E1E4E9"
    assert palette["color0"] == "#000511"
    assert palette["color7"] == "#CCD0D7"


def test_ignores_comments_and_non_color_lines():
    palette = theme.parse_palette(SAMPLE)
    assert "generated" not in palette
    assert len(palette) == 4


def test_returns_empty_on_garbage():
    assert theme.parse_palette("this is not lua") == {}


def test_fallback_used_when_palette_empty():
    css = theme.build_css("", "window { background: @background; }")
    assert "@define-color background" in css
    assert "window { background: @background; }" in css


def test_build_css_prepends_definitions():
    css = theme.build_css(SAMPLE, "card { color: @foreground; }")
    assert "@define-color foreground #E1E4E9;" in css
    assert css.index("@define-color") < css.index("card {")


def test_load_palette_text_missing_file_returns_empty(tmp_path):
    assert theme.load_palette_text(tmp_path / "nope.lua") == ""
