# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(00010E)
$foreground = rgb(E1E4E9)
$color0 = rgb(000511)
$color1 = rgb(0C3B57)
$color2 = rgb(0E3F5C)
$color3 = rgb(464443)
$color4 = rgb(55463D)
$color5 = rgb(4B6477)
$color6 = rgb(7F858F)
$color7 = rgb(CCD0D7)
$color8 = rgb(8F9196)
$color9 = rgb(104E74)
$color10 = rgb(13547B)
$color11 = rgb(5E5A59)
$color12 = rgb(715D52)
$color13 = rgb(64859F)
$color14 = rgb(AAB1BF)
$color15 = rgb(CCD0D7)
